apiVersion: v1
kind: Service
metadata:
  name: silverbullet
  namespace: silverbullet
spec:
  selector:
    app: silverbullet
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
